"""add certificate domain foreign key

Revision ID: 07336ada8033
Revises: 18ef2ca64bfe
Create Date: 2026-09-08 09:11:24.925324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07336ada8033'
down_revision: Union[str, Sequence[str], None] = '18ef2ca64bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_certificates_domain_id_domains'), 'certificates', 'domains', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_certificates_domain_id_domains'), 'certificates', type_='foreignkey')
    # ### end Alembic commands ###
