"""create scan history table

Revision ID: 1509cdd993be
Revises: 07336ada8033
Create Date: 2026-09-09 10:34:26.988232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1509cdd993be'
down_revision: Union[str, Sequence[str], None] = '07336ada8033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_scan_history_certificate_id_certificates')),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_scan_history_domain_id_domains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_history'))
    )
    op.create_index(op.f('ix_scan_history_certificate_id'), 'scan_history', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_scan_history_domain_id'), 'scan_history', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_history_domain_id'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_certificate_id'), table_name='scan_history')
    op.drop_table('scan_history')
    # ### end Alembic commands ###
