"""track certificate changes

Revision ID: 64545567b732
Revises: 3067daedaa75
Create Date: 2026-10-01 15:08:55.510353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64545567b732'
down_revision: Union[str, Sequence[str], None] = '3067daedaa75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "scan_history",
        sa.Column(
            "certificate_changed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.alter_column(
        "scan_history",
        "certificate_changed",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_history', 'certificate_changed')
    # ### end Alembic commands ###
