"""add notification events

Revision ID: 845056ad805f
Revises: 64545567b732
Create Date: 2026-10-07 05:46:03.442593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845056ad805f'
down_revision: Union[str, Sequence[str], None] = '64545567b732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_notification_events_domain_id_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events'))
    )
    op.create_index(op.f('ix_notification_events_domain_id'), 'notification_events', ['domain_id'], unique=False)
    op.create_index(op.f('ix_notification_events_event_key'), 'notification_events', ['event_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_events_event_key'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_domain_id'), table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
