"""add certificate fingerprint

Revision ID: 97d83910ae9d
Revises: 1509cdd993be
Create Date: 2026-09-30 16:47:36.430807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d83910ae9d'
down_revision: Union[str, Sequence[str], None] = '1509cdd993be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "certificates",
        sa.Column(
            "fingerprint_sha256",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_certificates_fingerprint_sha256"),
        "certificates",
        ["fingerprint_sha256"],
        unique=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_fingerprint_sha256'), table_name='certificates')
    op.drop_column('certificates', 'fingerprint_sha256')
    # ### end Alembic commands ###
